services:
  mysql80_eloquent_expansion_development:
    container_name: mysql80_eloquent_expansion_development
    build:
      context: .
      dockerfile: ./.docker/dockerfile/MySQL80_Dockerfile
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tests
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    # 永続化は不要
    # volumes:
    #   - ./mysql_data:/var/lib/mysql
    volumes:
      # 起動時にSQLを実行する
      - ./.docker/mysql-init:/docker-entrypoint-initdb.d

  php74_eloquent_expansion_development:
    container_name: php74_eloquent_expansion_development
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    restart: unless-stopped
    command: >
      bash -c '
        composer update;
        tail -f /dev/null;
      '
    depends_on:
      - mysql80_eloquent_expansion_development
