name: Review Reminder

on:
  workflow_dispatch:
  schedule:
    # 火曜日の AM10:00 に実行
    - cron: '0 1 * * 2'

jobs:
  notify_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get open pull requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls \
               | jq -r '.[] | select(.requested_reviewers | length > 0) | {number: .number, title: .title, url: .html_url, reviewers: .requested_reviewers[].login}' \
               > prs.json

      - name: show json
        run: cat prs.json

      - name: Notify reviewers via GitHub comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -s prs.json ]; then
            cat prs.json | jq -c '.[]' | while read -r row; do
              pr_number=$(echo "$row" | jq -r '.number')
              pr_title=$(echo "$row" | jq -r '.title')
              reviewers=$(echo "$row" | jq -r '.reviewers')

              message=":bell: **Reminder**: The pull request [#${pr_number} - ${pr_title}](https://github.com/kanagama/laravel-eloquent-method-expansion/pull/${pr_number}) is waiting for your review.\nReviewers: ${reviewers}"

              curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
                  -H "Content-Type: application/json" \
                  -d "{\"body\": \"$message\"}" \
                  "https://api.github.com/repos/kanagama/laravel-eloquent-method-expansion/issues/${pr_number}/comments"
            done
          else
            echo "No pending reviews."
          fi
