name: PHPUnit test

on:
  pull_request:

jobs:
  phpunit-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tests
        ports:
          - 13306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      max-parallel: 5
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]
        library:
          - { laravel: ^10.0 }
          - { laravel: ^9.0 }
          - { laravel: ^8.0 }
        exclude:
          - { php: 7.4, library: { laravel: ^9.0 } }
          - { php: 7.4, library: { laravel: ^10.0 } }
          - { php: 8.0, library: { laravel: ^10.0 } }
          - { php: 8.1, library: { laravel: ^8.0 } }
          - { php: 8.2, library: { laravel: ^8.0 } }

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, zip, xml

    - name: Laravel Install
      run: |
        composer require --dev "laravel/framework:${{ matrix.library.laravel }}"

    - name: Run PHPUnit Test
      run: |
        vendor/bin/phpunit tests/Unit/
      env:
         DB_HOST: 127.0.0.1
