name: Static Analysis

on:
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, zip, xml

    - name: Run Static Analysis
      run: |
        php vendor/bin/phpstan analyse -l 3 src/
